PRAGMA foreign_keys = ON;

CREATE TABLE users (id TEXT PRIMARY KEY, personal_number TEXT NOT NULL UNIQUE, username TEXT NOT NULL UNIQUE, email TEXT UNIQUE, phone TEXT, password_hash TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('active','pending','suspended')), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE member_profiles (user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, first_name TEXT NOT NULL, last_name TEXT NOT NULL, birth_date TEXT, parish TEXT, level TEXT, father_name TEXT, mother_name TEXT, avatar_url TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE admin_roles (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, is_principal INTEGER NOT NULL DEFAULT 0 CHECK(is_principal IN (0,1)), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE admin_assignments (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, role_id TEXT NOT NULL REFERENCES admin_roles(id), scope TEXT NOT NULL DEFAULT 'all', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE authorities (id TEXT PRIMARY KEY, name TEXT NOT NULL, title TEXT NOT NULL, bio TEXT, image_url TEXT, type TEXT NOT NULL CHECK(type IN ('founder','spiritual','variable')), display_order INTEGER NOT NULL DEFAULT 0, is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0,1)), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE site_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE media_assets (id TEXT PRIMARY KEY, url TEXT NOT NULL, alt_text TEXT, kind TEXT NOT NULL CHECK(kind IN ('image','video','document')), uploaded_by TEXT REFERENCES users(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE trainings (id TEXT PRIMARY KEY, title TEXT NOT NULL, summary TEXT NOT NULL, report_url TEXT, cover_url TEXT, video_url TEXT, price_cfa INTEGER NOT NULL DEFAULT 0 CHECK(price_cfa >= 0), whatsapp_url TEXT, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','published')), published_at TEXT, created_by TEXT REFERENCES users(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE training_testimonials (id TEXT PRIMARY KEY, training_id TEXT NOT NULL REFERENCES trainings(id) ON DELETE CASCADE, user_id TEXT REFERENCES users(id), author_name TEXT NOT NULL, rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5), content TEXT NOT NULL, is_published INTEGER NOT NULL DEFAULT 0 CHECK(is_published IN (0,1)), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE training_enrollments (id TEXT PRIMARY KEY, training_id TEXT NOT NULL REFERENCES trainings(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, payment_status TEXT NOT NULL DEFAULT 'pending' CHECK(payment_status IN ('not_required','pending','paid')), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(training_id,user_id));
CREATE TABLE events (id TEXT PRIMARY KEY, title TEXT NOT NULL, summary TEXT NOT NULL, location TEXT, facilitator TEXT, starts_at TEXT NOT NULL, ends_at TEXT, visibility TEXT NOT NULL DEFAULT 'public' CHECK(visibility IN ('public','members','selected')), created_by TEXT REFERENCES users(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE event_registrations (id TEXT PRIMARY KEY, event_id TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, status TEXT NOT NULL DEFAULT 'registered' CHECK(status IN ('registered','attended','cancelled')), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(event_id,user_id));
CREATE TABLE merits (id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id), title TEXT NOT NULL, reason TEXT NOT NULL, distinction TEXT, image_url TEXT, is_public INTEGER NOT NULL DEFAULT 1 CHECK(is_public IN (0,1)), awarded_by TEXT REFERENCES users(id), awarded_at TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE sanctions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, title TEXT NOT NULL, reason TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','resolved','appealed')), issued_by TEXT REFERENCES users(id), issued_at TEXT NOT NULL, resolved_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE notifications (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, title TEXT NOT NULL, content TEXT NOT NULL, read_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE INDEX idx_members_name ON member_profiles(last_name, first_name);
CREATE INDEX idx_events_starts_at ON events(starts_at);
CREATE INDEX idx_sanctions_user ON sanctions(user_id, issued_at);
CREATE INDEX idx_notifications_user ON notifications(user_id, read_at);
