import styles from "../../components/Showcase.module.css";

export default function AboutPage() {
  const leaders = [["F", "Autorité fondatrice", "Repère permanent"], ["S", "Autorité spirituelle", "Repère permanent"], ["P", "Présidence ADS", "Responsabilité évolutive"], ["C", "Conseil des responsables", "Responsabilité évolutive"]];
  return <main className={styles.page}>
    <section className={styles.hero}><p className={styles.eyebrow}><span /> Notre histoire et nos valeurs</p><h1>Une fraternité<br /><em>qui fait grandir.</em></h1><p className={styles.lead}>ADS, Fraternité, Jeunes Leaders est un mouvement catholique de jeunesse du Diocèse de Porto-Novo, enraciné dans la foi, le service et l&apos;excellence chrétienne.</p></section>
    <section className={styles.section}><div className={styles.video}><div className={styles.videoFrame}><button className={styles.play} aria-label="Lire la vidéo de présentation"><i className="fa-solid fa-play" /></button></div><div className={styles.videoCopy}><h2>Découvrir le groupe ADS</h2><p>Une brève présentation de notre mouvement, de ses jeunes et de son engagement au service de l&apos;Église et de la société.</p><p className={styles.note}>La vidéo sera publiée par l&apos;administration.</p></div></div></section>
    <section className={styles.sectionAlt}><div className={styles.heading}><h2>Notre mission</h2><p>Former des jeunes responsables, fraternels et capables de mettre leurs talents au service des autres.</p></div><div className={styles.cards}>{[["fa-cross","Foi vivante","Grandir dans une relation personnelle avec Dieu."],["fa-hand-holding-heart","Service","Agir concrètement pour sa communauté."],["fa-people-group","Union","Avancer ensemble dans une fraternité exigeante."]].map(([icon,title,text])=><article className={styles.card} key={title}><i className={`fa-solid ${icon}`} /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className={styles.section}><div className={styles.heading}><h2>Les autorités du mouvement</h2><p>Le fondateur et l&apos;autorité spirituelle sont les repères permanents d&apos;ADS. Les autres responsables seront ajoutés et mis à jour depuis l&apos;administration.</p></div><div className={styles.people}>{leaders.map(([letter,name,role],index)=><article className={styles.person} key={name}><div className={styles.avatar}>{letter}</div><h3>{name}</h3><p className={index < 2 ? styles.fixed : ""}>{role}</p>{index > 1 && <small>Profil administrable</small>}</article>)}</div></section>
  </main>;
}
